---
title: "Example BEDASSLE run: teosinte"
author: Peter Ralph
date: March 25, 2015
---

Here are all the objects saved in the output:
```{r setup}
library(BEDASSLE)
show(load("teosinte/zea_MCMC_output.Robj"))
fig.dim <- 5
require(knitr)
opts_chunk$set(fig.height=fig.dim,fig.width=2*fig.dim,fig.align='center')
```

Diagnostics
-----------

First, let's look at traces of the $\alpha$ parameters and their acceptance rates:
```{r third_as}
layout(t(1:2))
plot(aD[-(1:1000)], xlab="MCMC generation", ylab="value", main="aD")
plot((aD_accept/aD_moves)[-(1:1000)], xlab="MCMC generation", ylab="", main="aD acceptance", ylim=c(0,1))
plot(as.vector(aE)[-(1:1000)], xlab="MCMC generation", ylab="value", main="aE")
plot((aE_accept/aE_moves)[-(1:1000)], xlab="MCMC generation", ylab="", main="aE acceptance", ylim=c(0,1))
plot(a2[-(1:1000)], xlab="MCMC generation", ylab="value", main="a2")
plot((a2_accept/a2_moves)[-(1:1000)], xlab="MCMC generation", ylab="", main="a2 acceptance", ylim=c(0,1))
```


And, the log-likelihood trace:
```{r loglikelihood}
plot(Prob[-(1:1000)], xlab="MCMC generation", main="log likelihood")
```
and mean acceptance rates for the allele-specific global mean ($\mu$) and population mean ($\Theta$) parameters:
```{r other_params}
plot((mu_accept/mu_moves)[-(1:1000)], xlab="MCMC generation", ylab="", main="mu acceptance", ylim=c(0,1) )
plot((thetas_accept/thetas_moves)[-(1:1000)], xlab="MCMC generation", ylab="", main="thetas acceptance", ylim=c(0,1) )
```


Here are autocorrelation traces of the $\alpha$ parameters:
```{r acf}
acf(a0[-(1:1000)],lag.max=10000,xlab='',ylab='')
acf(a2[-(1:1000)],lag.max=10000,xlab='',ylab='')
acf(as.vector(aE)[-(1:1000)],lag.max=10000,xlab='',ylab='')
acf(aD[-(1:1000)],lag.max=10000,xlab='',ylab='')
```

Also, joint traces of parameters:
```{r joint_marginals, fig.height=3*fig.dim}
layout(matrix(1:6,nrow=3))
cols <- adjustcolor(rainbow(64)[cut(seq_along(a0),breaks=64)],0.5)
varnames <- c("aD","aE","a2","a0")
for (i in 1:3) {
    for (j in (i+1):4) {
        plot( as.vector(get(varnames[i]))[-(1:1000)], as.vector(get(varnames[j]))[-(1:1000)], col=cols, pch=20, xlab=varnames[i], ylab=varnames[j] ) 
    }
}
```


Results
-------

Here's the main thing we are interested in:
the posterior distribution of the ratio of the relative strengths of $\alpha_E$ and $\alpha_D$:
```{r ratio_posterior}
hist((aE/aD)[-(1:1000)],breaks=100,main="posterior of aE/aD ratio")
```


